#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: ZwF65Rl156oMAenHhi8BAY0LySWhhjDvNNt91dpU7D5N88E8ToZyZHCziktv7sz3

os:
- wmf5
- Ubuntu1804

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /NO_CI.*|updated readme.*|update readme.*s/

build: false

test_script:
  - ps: . .\build.ps1 -Task Test

for:
-
  matrix:
    only:
      - os: wmf5

  deploy_script:
    - ps: . .\build.ps1 -Task Deploy
